[package]
name = "gmod_engine"
description = "Binary module that accesses engine.dll"
version = "0.4.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rglua = { path = "../../rglua" }
