[package]
name = "gmod_engine"
description = "Binary module that accesses engine.dll"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rglua = { path = "../.." }
anyhow = "1.0.51"