[package]
name = "rglua"
description = "Rust bindings to the lua api for gmod binary module creation"
version = "0.1.1"
authors = ["Vurv <vurvdevelops@gmail.com>"]
keywords = ["glua","garrysmod","lua"]
readme = "README.md"
license = "MIT"
edition = "2018"

# Remember to make your output module a cdylib.

[dependencies]
#dlopen = { git = "https://github.com/Vurv78/rust-dlopen", branch = "future", features = ["derive"] }
dlopen = "0.1.8"
once_cell = "1.7.2"
const-cstr = "0.3.0"